Fix text in walkthrough
teamtomo/teamtomo-site-archive pull request #58
Opened 2022-09-28 21:41 UTC by dmichalak

Related to https://github.com/teamtomo/teamtomo.github.io/issues/57#issue-1388280301 and includes 2 other fixes.

2022-09-29 09:35 UTC, brisvag requested changes
Thanks for the PR! I have suggested some small change.

2022-09-29 09:35 UTC, brisvag commented on walkthroughs/EMPIAR-10164/m.md
> +Provide this mask to `M`, and then we need to reformat the final particle positions `.star` file using `relion_star_downgrade` to the Relion3.0 specification (Warp does not support Relion 3.1+):
```suggestion
If using Relion3.1+, we need to reformat the final particle positions `.star` file using `relion_star_downgrade` to the Relion3.0 specification (Warp does not support Relion 3.1+): 
```

2022-09-29 09:35 UTC, brisvag commented on walkthroughs/EMPIAR-10164/particle-picking.md
> +This confirms the previously measured interparticle distance and the fact that most particles slid into ordered positions in the lattice. We can use the first peak to select against particles that do
I would leave it here as well, since `dtneighbours_in_range` *is* required by [`subset_table_based_on_neighbours.m`](https://github.com/teamtomo/teamtomo.github.io/blob/master/walkthroughs/EMPIAR-10164/scripts/subset_table_based_on_neighbours.m) as well. I should be in both places!

2022-09-29 14:32 UTC, dmichalak commented on walkthroughs/EMPIAR-10164/particle-picking.md
> +This confirms the previously measured interparticle distance and the fact that most particles slid into ordered positions in the lattice. We can use the first peak to select against particles that do
Makes sense. I don't see the option to commit this suggested change. This is my first time going through this process so I might be missing something obvious.

2022-09-29 15:14 UTC, brisvag commented on walkthroughs/EMPIAR-10164/particle-picking.md
> +This confirms the previously measured interparticle distance and the fact that most particles slid into ordered positions in the lattice. We can use the first peak to select against particles that do
It's because this was not a suggested change, just a comment, so you got everything right :P

2022-09-30 15:36 UTC, dmichalak commented on walkthroughs/EMPIAR-10164/particle-picking.md
> +This confirms the previously measured interparticle distance and the fact that most particles slid into ordered positions in the lattice. We can use the first peak to select against particles that do
Oh okay. I'll add another change to the PR to include this then.

Edit: Should be good to go!

2022-09-30 15:51 UTC, brisvag approved these changes
great, thanks!

2022-09-30 15:51 UTC, merged